version: '3'
services:
  cwlrunner:
    build: .
    ports:
      - "5002:5002"
    environment:
      - MINIO_DOCKER_NAME=minio:9000
      - MINIO_ACCESS_KEY=Minio
      - MINIO_SECRET_KEY=secret123
  validator:
    image: jniestroy/json_validation
    ports:
      - "5000:5000"
  dataset_service:
    image: jniestroy/dataset_service
    ports:
      - "5005:5005"
    environment:
      - MINIO_DOCKER_NAME=minio:9000
      - MINIO_ACCESS_KEY=Minio
      - MINIO_SECRET_KEY=secret123

  minio:
      image: minio/minio
      command: ["server", "/data"]
      ports:
        - "9000:9000"
      environment:
        - MINIO_DOCKER_NAME=minio
        - MINIO_ACCESS_KEY=Minio
        - MINIO_SECRET_KEY=secret123
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo_secret
  ors:
    image: jniestroy/old_ors
    ports:
      - "8080:8080"
    environment:
      - MONGO_ROOT_USERNAME=mongo
      - MONGO_ROOT_PASSWORD=mongo_secret
      - MONGO_SERVER=mongodb
